dist: trusty
sudo: required

language: c
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=1.2.0
  - MRUBY_VERSION=master
matrix:
  allow_failures:
    - env: MRUBY_VERSION=master
branches:
  only:
    - master
addons:
  apt:
    packages:
      - wget
      - rake
      - bison
      - git
      - gperf
      - texinfo
      - automake
      - autoconf
      - autotools-dev

install:
  - mkdir ~/src
  - cd ~/src && wget http://git.savannah.gnu.org/cgit/automake.git/snapshot/automake-1.15.tar.gz && tar xzf automake-1.15.tar.gz && cd -
  - cd ~/src/automake-1.15 && ./bootstrap.sh && ./configure --prefix=/usr && make && sudo make install && cd -
script:
  - rake test
